sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.projectName=Meridian Blog
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/*.db,\
  **/*.pdf,\
  **/uploads/**,\
  **/coverage/**,\
  **/.github/**,\
  **/public/icons/**

sonar.javascript.file.suffixes=.js,.mjs,.cjs,.vue
sonar.typescript.file.suffixes=.ts,.tsx

sonar.python.version=3

sonar.javascript.lcov.reportPaths=\
  auth-service/coverage/lcov.info,\
  blog-service/coverage/lcov.info,\
  media-service/coverage/lcov.info,\
  api-gateway/coverage/lcov.info,\
  frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
